### ISSUE TITLE
Checkbox HBS and js code

### ISSUE THREAD

**Issue by zurnet** [onechiporenko/ember-models-table#174]
I'm trying to follow this [example](http://onechiporenko.github.io/ember-models-table/#/examples/select-rows-with-checkboxes) for checkboxes.

One thing I'm unsure about is where is the js and/or hbs code for the following:
    "template": "custom/checkbox",
    "templateForSortCell": "custom/checkbox-all

I know I need to create these files, but what goes in the hbs and the corresponding js for them?

Is there an example for what is supposed to go into those template files?

**Comment by zurnet** [comment]
In addition to this, it would be helpful to see an example of how to pass data into the datatable to have rows 'already selected' if you've previously selected them in your program for the record(s) you're keeping track of.

**Comment by onechiporenko** [comment]
Hi, @zurnet.

First of all, you should extend `models-table` and add action:

```javascript
actions: {
    toggleAllSelection() {
      let selectedItems = get(this, '_selectedItems');
      let data = get(this, 'data');
      if(selectedItems.length === data.length) {
        get(this, '_selectedItems').clear();
      }
      else {
        set(this, '_selectedItems', A(data.slice()));
      }
      this.userInteractionObserver();
    }
  }
```

Both templates for checkboxes are here:

`app/templates/custom/checkbox.hbs` (https://github.com/onechiporenko/ember-models-table/blob/master/tests/dummy/app/templates/custom/checkbox-all.hbs):

```handlebars
<span class="glyphicon {{if (exists-in _selectedItems record) "glyphicon-check" "glyphicon-unchecked"}}"></span>
```
`app/templates/custom/checkbox-all.hbs` (https://github.com/onechiporenko/ember-models-table/blob/master/tests/dummy/app/templates/custom/checkbox-all.hbs):

```handlebars
<span {{action "toggleAllSelection"}} class="glyphicon {{if (is-equal _selectedItems.length data.length) "glyphicon-check" "glyphicon-unchecked"}}"></span>
```
Fill free to put them anywhere you need (just update pathes in the column-definition).

> In addition to this, it would be helpful to see an example of how to pass data into the datatable to have rows 'already selected' if you've previously selected them in your program for the record(s) you're keeping track of.

You may try to set `_selectedItems` on component init with records that are "already selected":
```javascript
selectRowsAfterInit: on('didInsertElement', function () {
  set('_selectedItems', ... );
})
```
You also need to set `multipleSelect` `true`.

You can't bind `_selectedItems` in the `{{models-table _selectedItems=some}}` because on component init value for `_selectedItems` is set to `[]`.

I didn't check described solutions, so if it not work fill free to ask here more.

**Comment by zurnet** [comment]
This all looks great, looking forward to testing it out!  Ember Models Table is a lifesaver!
