### ISSUE TITLE
No popup display for showColumnsDropdown

### ISSUE THREAD

**Issue by optikalefx** [onechiporenko/ember-models-table#188]
Just installed the addon, and the popup for the column selector doesn't show up. Nothing in the DOM seems to change, and there are no errors. Any ideas on the first place to look to debug that?

**Comment by phndiaye** [comment]
I recently had a similar issue, but it was not coming from the library. It was because I was importing `bootstrap.js` multiple times. Once in my own addon that uses ember-models-table, and a second time in my app's `ember-cli-build.js` file.

I had it while working on an addon, tho. So I don't know if that's a special case, but maybe it's the same issue :)

**Comment by optikalefx** [comment]
I have `ember-bootstrap` installed in my app already. Are you saying that you can't have bootstrap for the addon to work?

**Comment by optikalefx** [comment]
`"ember-bootstrap": "1.0.0-alpha.5",`

**Comment by onechiporenko** [comment]
@optikalefx, `ember-bootstrap` doesn't provide `bootstrap.js` to your app. 
If you don't want/don't need it and you are using `ember-bootstrap`, you may create your own `app/templates/dropdown.hbs`:
```handlebars
{{#bs-dropdown class="pull-right" as |dd|}}
  {{#dd.button}}{{messages.columns-title}} <span class="caret"></span>{{/dd.button}}
  {{#dd.menu as |menu|}}
    {{#menu.item}}
      <a {{action "showAllColumns" column bubbles=false}} href="#">{{messages.columns-showAll}}</a>
    {{/menu.item}}
    {{#menu.item}}
      <a {{action "hideAllColumns" column bubbles=false}} href="#">{{messages.columns-hideAll}}</a>
    {{/menu.item}}
    {{#menu.item}}
      <a {{action "restoreDefaultVisibility" column bubbles=false}} href="#">{{messages.columns-restoreDefaults}}</a>
    {{/menu.item}}
    {{menu.divider}}
    {{#each processedColumns as |column|}}
      {{#if column.mayBeHidden}}
        {{#menu.item}}
          <a {{action "toggleHidden" column bubbles=false}} href="#">
            <span class="{{if column.isVisible icons.column-visible icons.column-hidden}}"></span> {{column.title}}
          </a>
        {{/menu.item}}
      {{/if}}
    {{/each}}
  {{/dd.menu}}
{{/bs-dropdown}}
```
Component usage going to be like this:
```handlebars
{{models-table data=data columns=columns columnsDropdownTemplate="dropdown"}}
```

**Comment by optikalefx** [comment]
I'll give this a shot, but do you know what the issue is? I wonder if there's something I can fix in the addon.

**Comment by onechiporenko** [comment]
@optikalefx, https://github.com/onechiporenko/ember-models-table#requirements
I didn't provide any bootstrap-files from my side to allow users do this (add bootstrap) in any way they need it.

**Comment by optikalefx** [comment]
@onechiporenko thanks! I didn't read carefully enough that ember-bootstrap didn't include the JS.  Good design choice actually on you and them. Thanks!

**Comment by Caltor** [comment]
@onechiporenko I've got this working by adding the following line to my ember-cli-build.js file.
`app.import('bower_components/bootstrap/dist/js/bootstrap.js');`
Could you change the columns-dropdown.hbs to use ember-bootstrap components instead of plain bootstrap.js please? That would mean the Columns button dropdown just works "out of the box" and I wouldn't need to have a bower dependency.
