### ISSUE TITLE
Filter by multiple values?

### ISSUE THREAD

**Issue by Caltor** [onechiporenko/ember-models-table#229]
Is it possible to filter by multiple values? So for example I would like to filter to show records with a status of 'Active' or 'Open'. At the moment I can only filter by one or the other. If not could I raise this as an enhancement request please as my users have asked for it. Many thanks.

**Comment by ScottShannon** [comment]
Are you using local-table or models-table-server-paginated?  If you are using models-table-server-paginated, I might have an idea. I'm not a veteran with this addon, but it seems you may be able to pass in your own partial to `headerFilteringRowTemplate`, use the current one as the template for yours and use something like [ember-power-select](https://github.com/cibernox/ember-power-select) instead of models-select.  You may need to join the array onchange and split the string for selected.  Hopefully someone more familiar with the source can confirm if this is an effective approach that won't destroy the logic in the actions

**Comment by Caltor** [comment]
@ScottShannon At the moment I'm just using {{models-table...}} which I presume is the same as local-table. I will probably be using models-table-server-paginated some time in the future, at which point I will revisit your idea, thanks. I'm kinda hoping the author might implement this in the meantime! :)

**Comment by onechiporenko** [comment]
Hi, @Caltor, @ScottShannon. 
Currently any filter may be implemented as separated component or separated template and combined with a custom filter function. 
It's possible that I'll implement this, but I can't give any estimates for it.
