### ISSUE TITLE
`get` is undefined (by cmonzon44)

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/ember-models-table#254]
I update to 2.0.0-beta.2 and common table throw me an error on console in firefox, 
`get(...) is undefined
_setupColumns@http://localhost:4200/assets/vendor.js:69428:24
exports.default<.setup<@http://localhost:4200/assets/vendor.js:69320:7`  on ember-metal:3988

Here my controller,
 ```js
import Ember from 'ember';
export default Ember.Controller.extend({
  columns: [{ propertyName: 'title', title: 'name' },
            { propertyName: 'artist', title: 'artis' },
            { propertyName: 'songCount', title: 'song' },
            ],
});
```

and here my simple model,  

```js
import DS from 'ember-data';
export default DS.Model.extend({
  title: DS.attr(),
    artist: DS.attr(),
    songCount: DS.attr()    
});
```

Before update version of ember and more components it was worked.

my actual versions:
```
DEBUG: Ember              : 2.15.0  index.js:158
DEBUG: Ember Data         : 2.15.0  index.js:158
DEBUG: jQuery             : 3.2.1  index.js:158
DEBUG: Ember Models Table : 2.0.0-beta.2  index.js:158
DEBUG: -------------------------------
```

Have i an error?

============

by @cmonzon44

**Comment by onechiporenko** [comment]
@cmonzon44, could you provide a loc where it happens? Thanks

**Comment by cmonzon44** [comment]
well, i could resolve, this problem. there was in my router because i never return de objects from store to layout.

model: function () {
            return this.get('store').findAll('pass');
  },

Now, i'm having another problem, -> **Uncaught TypeError: assign is not a function**

the line of problem is when models-table set de default or custom messages:

_setupMessages: observer('customMessages', function () {
      var customIcons = getWithDefault(this, 'customMessages', {});
      var newMessages = {};
      **assign(newMessages, defaultMessages, customIcons);**
      set(this, 'messages', O.create(newMessages));
    }),

![image](https://user-images.githubusercontent.com/11430219/30839324-9c690d9c-a247-11e7-97a7-66dfb8dfb667.png)

**Comment by cmonzon44** [comment]
after I upgrade to "^2.0.0-beta.3" its works but the template in custom column doesn't work.. any suggestions?

**Comment by onechiporenko** [comment]
https://github.com/onechiporenko/ember-models-table/issues/252#issuecomment-334697282
