### ISSUE TITLE
I want to show the image in one of the Rows?

### ISSUE THREAD

**Issue by Girjashanker** [onechiporenko/ember-models-table#293]
I have One row for User image. and how to show at the template. 

this is my template userlist.hbs 

```
{{models-table
  data=model
  columns=columns
  multipleSelect=true
}}

```

this is my controller userlist.js

```
  columns: [
    {
      "propertyName": "username"
    },
    {
      "propertyName": "role"
    },
    {
      "propertyName": "user_image"
    },
  ],
```

By using like this all data show in the template. But in user_image rows i want to show image not data.
please help me how to do. Thanks

**Comment by onechiporenko** [comment]
You can create a custom [component](http://onechiporenko.github.io/ember-models-table/v.2/docs/classes/Utils.ModelsTableColumn.html#property_component) and display it in the cell

**Comment by Girjashanker** [comment]
Hi Bro. Can you please explain me some details example of this how to do. Thanks you so much.

**Comment by Girjashanker** [comment]
I am Doing Like this.

I have One row for User image. and how to show at the template.

this is my template userlist.hbs

```
 {{models-table
   data=model
   columns=columns
   columnComponents=(hash deleteRow=(component "delete-row-comp" data=model))
 }}

```
this is my controller userlist.js
```
 
   columns: [
     {
       "propertyName": "username"
     },
     {
       "propertyName": "role"
     },
     {
       "propertyName": "user_url",
       "component": "deleteRow",
     },
   ],
 

```


And Now this is my component delete-row-comp.hbs

 ```
{{#each data as |item|}}

<img src={{item.user_url}} />

 {{/each}}
```

The result is now showing like this.



![screenshot_20180104_215820](https://user-images.githubusercontent.com/22745120/34571262-6f14a082-f19c-11e7-96bd-2c36f05d5e87.png)

There is two user data in user table but now showing all imgae in each cell. what I am wrong. please help me. Thanks.

**Comment by cah-briangantzler** [comment]
I changed the name, because its not a deleteRow usage, to show you how the names link up. You should change your component to user-image instead of delete-row-comp. You were passing the entire model (all items) into the component and showing them. You would do this if the component was not specific to a row. In your case it is.
```
 {{models-table
   data=model
   columns=columns
   columnComponents=(hash userImage=(component "delete-row-comp"))
 }}
```

Updated the name to show you the relation. You can have several components, then name is what links them
``` 
   columns: [
     {
       "propertyName": "username"
     },
     {
       "propertyName": "role"
     },
     {
       "propertyName": "user_url",
       "component": "userImage",
     },
   ],
 
```

Every component in the row is passed record (the data item for the row) and property name (The property name for the current column) amoung other fields, check the documentation for the other values passed

Here we are using record and hard coded the property.
```
<img src={{record.user_url}} />
```
or
this component uses the record passed and the property name passed making this component reusable for multiple columns of images, not just the user_url column,
```
<img src={{get record propertyName}} />
```

**Comment by Girjashanker** [comment]
Really Really Thanks Bro. Now Everything ok. Thank you so much.
