### ISSUE TITLE
Add ability to check when column titles are auto generated

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/ember-models-table#323]
* **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - ~[ ] support request~ Any support-request can be only in the Slack channel [#e-models-table](https://embercommunity.slack.com/messages/C8NTDUVGU/). 

* **What is the current behavior?**

Currently there is no way to check if column title is auto generated from property name (only manually)

* **[Feature] What is the motivation / use case for changing the behavior?**

Using multiple languages in your application require to set titles for columns manually and not generate them basing on properties shown in the columns.

New attribute `checkTextTranslations` with `true`-value will output warning in the console for each auto generated column's title. Message will be something like:

```
#{view-id}. No title. Column #{n}. {property-name}
```

Here `view-id` is an `elementId` of table, `n` - index of column in the `columns`-array and `property-name` is a property name used to generate title.

Warning won't appear if `title` is provided (even if it's empty).

```hbs
{{models-table 
  checkTextTranslations=true
  data=model
  columns=columns
}}
```
:warning:  `utils/fmt` is updated to handle `safeString`s properly.

**Comment by cah-briangantzler** [comment]
If its not too late. I would think a better name for the property would be requireColumnTitleProperty. The intent of what they are using it for is bleeding into the definition. If I were to see this in your docs I would assume that the component handles translations for me some how.

Also this variable is performing a check that if it fails, would be fixed, meaning this is more of a testing feature than a runtime feature. Good tests would tell the requestor they forgot the title property, adding the property to the component seems wrong.

An even better solution would be to pass models table a component that performs translation, if that component is present, use it, and use the property titleKey then falling back to propertyName as the translation key. Passing the component would be similar to setting this property true. The in the code they wouldnt need to do the translation, but instead just supply the key or use property name. If neither were found in the translation they would get the visible translation missing message. This accomplished the tell me when I forgot it (really a testing task not a runtime time) would would add the benefit of doing the translation (an actual runtime feature). 

If you are interested in the translation thing, I can make a pull request.

At the very least change the property to requireColumnTitleProperty and indicate what the check is actually doing instead of what one use case may do with the information

**Comment by onechiporenko** [comment]
@cah-briangantzler adding component is too complex solution as for me. However creating a mechanism similar to `i18n` 'missing-translation' is a good idea. 
When `checkTextTranslations` is `true` column title may be shown as `missing translation`. How about this/

**Comment by cah-briangantzler** [comment]
@onechiporenko I do like that better. It better suites the property name and I didn't care for the new visual div to report titles missing.

I can be on board with that.
