### ISSUE TITLE
editable dropdown

### ISSUE THREAD

**Issue by akursat** [onechiporenko/ember-models-table#331]
* **I'm submitting a ...**

  - [ ] bug report
  - [x ] feature request
  - ~[ ] support request~ Any support-request can be only in the Slack channel [#e-models-table](https://embercommunity.slack.com/messages/C8NTDUVGU/). 

* **What is the current behavior?**
The inline edit only works with inputs.

* **[Feature] What is the motivation / use case for changing the behavior?**
Can you develop editable dropdown in the inline edit mode?

* **Other information** 
here is a example https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml

**Comment by cah-briangantzler** [comment]
The inline edit contains all the hooks to allow you to create your own component. That was you can use the html select, power-select or the dropdown or your choice.

I can help you with this if you wish.

@onechiporenko should we create a component that uses the HTML select to be used as a default, but also would serve as an example should someone wish to adapt their own?

**Comment by onechiporenko** [comment]
@cah-briangantzler I have a demo with `power-select` used in the inline-edit:
https://ember-twiddle.com/99e1630b806bd4bd6edb5682429079a8?fileTreeShown=false

**Comment by akursat** [comment]
@onechiporenko thank you for your interest. I have easily adapted dropdown of semantic ui. I couldn't see similar example on the http://onechiporenko.github.io/ember-models-table/v.2/#/examples/in-line-edit. Can you add this example to the documentation?

@cah-briangantzler it'll be nice if you add columnType like input, select maybe radio button on columns section.  I didn't check your source but you probably have inline-input.hbs. I guess, you can customize here with if statements and columnType property.

**Comment by cah-briangantzler** [comment]
I dont think we provided a default for some of these things because it would have have to be a really raw default. Did not want to make the choice for you on what drop-down or radio button component to use. There are great ones out there. And more than likely the defaults shouldn't be used. Someone could easily create a new addon that provides a set of inputs to use.

The input default that was provided pretty much does handle the problem (Although it doesn't provide for validation for example). The default input is also an example on how you would adapt any other component.
