### ISSUE TITLE
[FEATURE REQUEST] Sort by async/promise properties 

### ISSUE THREAD

**Issue by BenjaminBeck** [onechiporenko/ember-models-table#343]
* **I'm submitting a ...**
  -  feature request

* **What is the motivation / use case for changing the behavior?**
All our ember-data relations are async. So many of our computed properties also are ``async`` functions.
Displaying them in a ember-models-table works with custom components.
But sorting and filtering does not work.

* **What is the current behavior?**
Sorting and filtering does not work if the property is a ``async`` function (Native Promise)

--------------------

* **Is there a solution i do not see without adding a new feature?**
* **Is this a feature that can be added to e.m.t.?**
* **Who can implement this or help?**

**Comment by onechiporenko** [comment]
Hi, @BenjaminBeck. It's a good feature to have. I'll think about its implementation.

**Comment by onechiporenko** [comment]
@BenjaminBeck, could you please provide a demo on ember-twiddle that doesn't work now? It'll help a lot to understand what is your vision of needed feature. Thanks

**Comment by BenjaminBeck** [comment]
@onechiporenko this twiddle shows a example https://ember-twiddle.com/4a907b966d0c071ba214ab0fe1e679f6
@cah-briangantzler yes, you are right, the cache-invalidation most likely does not work (didn´t test it). But the example shows the principle that promise objects can not be sorted no matter where they come from.

**Comment by BenjaminBeck** [comment]
I did some debugging to see if i could make this work with a custom sort function. But I think this is not possible at the moment because the complete call-stack of the sort function must be promise-aware.

**Comment by cah-briangantzler** [comment]
I believe the fundamental problem is here
```
   numberOfPhotos: Ember.computed('photos.[]', async function(){
    let photos = await this.get('photos');
    return photos.length;
  })
```
You cant have an async computed property. You simply cant have an async function for a computed property, the caching doesnt allow it.  It isnt so much the sort has to be async aware as you have to treat all computed properties as async aware.  If you wanted to sum the photos you would have to write the following 
```
async sum() {
     let sum = 0;
     this.albums.forEach((item) = {
          let numPhotos = await item.get('numberOfPhotos');
          sum += numPhotos;
    });
}
```
You had to KNOW to treat the computed property as a promise. An addon has no way of knowing which properties are async and which are not. Once you start to treat all computeds as potential promises, then what, you have to treat all properties as potential promises. From the code you cant tell what numberOfPhotos is. Could easily be just a field that contains a promise, doesnt have to be a computed. (Incidentally await is not allowed inside of forEach so the above is incorrect, just using for concept purposes)

Note that your computed property is ACTUALLY this 
```
   numberOfPhotos: Ember.computed('photos.[]', async function(){
    return this.get('photos');
  })
```

You see the await causes a return, and what ends up being cached is the promise. Then when  the promise succeeds and the return result happens, no one cares. The cache system is not waiting on the promise and cache is not updated with the result of the promise.

To solve this problem, ember data has promiseObjects and promiseArrays which you are not using correctly. I think you will find if you change your computed to the following, you will get better results.

```
   numberOfPhotos: Ember.computed('photos.[]', function(){
    return this.get('photos.length');
  })

or better yet
    numberOfPhotos: Ember.computed.reads("photos.length")  // actually you could just make propertyName in the column definition "photos.length" and do away with the computed altogether
```

Why does this work? Ember data returns a PromiseArray with the result of the array and length being zero. Once the promise is resolved, the array and length are updated (causing invalidation). So the initial value is zero, the array is resolved, the computed runs again and this time gets a result. NOTE: This works because photos is a PromiseArray NOT a regular Promise.

In your original computed you returned a promise (regular one, not a PromiseArray) (the await was the culprit making a return) and when the promise was resolved, the computed ran again, because of "photos.[]", which just returned the same promise (the await), not the result of the promise. This leaves promises cached for numberOfPhotos and not the results. When the sorting runs, objects that do not implement compareTo (Doesnt seem like something Promise would implement) are considered equal, hence no sorting. Its also why the filter says nothing matches, you are comparing what is in the filter with a promise, not the result of the promise.

As an aside, the difference between photos.length and photos.[] is that if the length doesnt change, the computed will not be fired again.. The caveat is that if you remove and item and add an item in the same cycle, the length doesnt change. For you thats ok, but for say a filter, you need the filter to run again and so use photos.[].

End result, yes the entire sort function would have to be promise aware, but the sort function is a loop,  and every iteration of the loop would execute two promises, original and compare. You could see how this could negatively impact performance. And once the promises are resolved they are still promises,   so when you sort again they still have to be awaited on and resolved, (yes they dont make a network call again, but they still go through the resolution process to return the previous result). 

PromiseObjects and PromiseArrays solve a lot of this problem if used correctly, however they implemented this via proxies which is why you can not use this.numberOfPhotos like you could for a computed (in Ember 3.1 or greater)but NOT on an ember data model .

So lots to digest there. But I think sorting / filtering on a promise is a very complex thing.

**Comment by BenjaminBeck** [comment]
@cah-briangantzler Thanks for your input. Unfortunately I have very little time until the end of the month. Maybe it will take until then for me to have a closer look at all your points.

**Comment by cah-briangantzler** [comment]
I forked your twiddle, changed the column definition in application controller for photos (1) from numberOfPhotos to photos.length, and you will see what I am talking about. The first column is now sortable and filterable 

https://ember-twiddle.com/07d801e389a5fc3b795cbb8068b457a1
