### ISSUE TITLE
Closure actions in custom components

### ISSUE THREAD

**Issue by gilles-bertrand** [onechiporenko/ember-models-table#349]
* **I'm submitting a support Request **
* **What is the current behavior?**
We are trying to use closure actions without sendActions inside a custom component. But nothing happens.

* **[Support] What exactly you try to do?**
We have a custom component
```import Component from '@ember/component';

export default Component.extend({
    onCheck(){},
    actions:{
        onCheckActive(){
            console.log("1");
            this.onCheck();
        }
    }
});
Component js
{{input type="checkbox" checked=(mut record.leader) click=(action "onCheckActive")}}
component hbs
```
Then a route with our ember models table
```
template.hbs
{{#models-table data=model.householder.value.householder.familycontacts columns=columnsContact showGlobalFilter=false editRow="editContactRow" deleteRow="deleteContactRow" onCheck=(action "onCheckActive") class="p-6 mt-4 ml-2 mr-2 mb-2 bg-white rounded" as |mt|}}
            {{#mt.table as |table|}}
                {{#table.header as |header|}}
                {{header.row-sorting}}
                {{/table.header}}
                {{table.body}}
            {{/mt.table}}
            <div class="w-full flex justify-center">
                <svg {{action "addContact"}} class="h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                    <path d="M11 9V5H9v4H5v2h4v4h2v-4h4V9h-4zm-1 11a10 10 0 1 1 0-20 10 10 0 0 1 0 20z"/>
                </svg>
            </div>
            {{/models-table}}
controller.js
columnsContact: computed(function(){
        return [
        {
            propertyName: 'name',
            title: this.get('intl').t('parameters.recipients.householder.name'),
            editable: false,
            useFilter: true, 
            mayBeHidden: false 
        },
        {
            propertyName: 'firstName',
            title: this.get('intl').t('parameters.recipients.householder.firstName'),
            editable: false,
            useFilter: true, 
            mayBeHidden: false 
        },
        {
            propertyName: 'email',
            title: this.get('intl').t('parameters.recipients.householder.contact.email'),
            editable: false,
            useFilter: true, 
            mayBeHidden: false,
            component: "recipients/householder/edit-checkbox"
        },
        {
            propertyName: 'leader',
            title: "Active",
            editable: false,
            useFilter: true, 
            mayBeHidden: false 
        },
        {
            title: "",
            editable: false,
            useFilter: true, 
            mayBeHidden: false ,
            component: "edit-delete-row-button"
        },
        ]
    }),
```

* **Please tell us about your environment:**

- `ember-models-table` version: 2.9
- `ember` version: 3.7.1
- `ember-data` version: 3.7.0
- `ember-cli` version:  3.7.1
- `node` version:11.9.0
- `npm` or `yarn` version: 6.5.0

**Comment by onechiporenko** [comment]
Hi, @gilles-bertrand. I didn't get which action you are trying to send. Could you create a demo on ember-twiddle? Thanks

**Comment by gilles-bertrand** [comment]
Hi @onechiporenko, here is a twiddle [twiddle](https://ember-twiddle.com/b211a6a3126d0b8378148d12fcdd442c?openFiles=controllers.application.js%2Ctemplates.components.edit-checkbox.hbs).
So when you click on the checkbox we where hoping to execute an alert like the button. But the action doesn't come to our action, we want to avoid sendAction since it's deprecated.
Thanks for your time.

**Comment by cah-briangantzler** [comment]
Hmmm, I thought this was better documented.

When you use `component: "component-name"` the component is invoked within the system and it is not possible trap any actions sent from that component.

The piece you are missing is defining the component hash on the table itself.  The component name in the column definition can be any name you want, it is matched to this component hash. If the name is not found, it then uses that name to invoke a component (meaning it must be a component name if not in the hash)

```
template.hbs
{{#models-table data=model.householder.value.householder.familycontacts columns=columnsContact showGlobalFilter=false editRow="editContactRow" deleteRow="deleteContactRow" onCheck=(action "onCheckActive") class="p-6 mt-4 ml-2 mr-2 mb-2 bg-white rounded" 
columnComponents=(hash
     deleteMe=(component "edit-delete-row-button" onClick=(action "deleteRow"))
)
as |mt|}}
            {{#mt.table as |table|}}
                {{#table.header as |header|}}
                {{header.row-sorting}}
                {{/table.header}}
                {{table.body}}
            {{/mt.table}}
            <div class="w-full flex justify-center">
                <svg {{action "addContact"}} class="h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                    <path d="M11 9V5H9v4H5v2h4v4h2v-4h4V9h-4zm-1 11a10 10 0 1 1 0-20 10 10 0 0 1 0 20z"/>
                </svg>
            </div>
            {{/models-table}}
controller.js
columnsContact: computed(function(){
        return [
        {
            propertyName: 'name',
            title: this.get('intl').t('parameters.recipients.householder.name'),
            editable: false,
            useFilter: true, 
            mayBeHidden: false 
        },
        {
            propertyName: 'firstName',
            title: this.get('intl').t('parameters.recipients.householder.firstName'),
            editable: false,
            useFilter: true, 
            mayBeHidden: false 
        },
        {
            propertyName: 'email',
            title: this.get('intl').t('parameters.recipients.householder.contact.email'),
            editable: false,
            useFilter: true, 
            mayBeHidden: false,
            component: "recipients/householder/edit-checkbox"
        },
        {
            propertyName: 'leader',
            title: "Active",
            editable: false,
            useFilter: true, 
            mayBeHidden: false 
        },
        {
            title: "",
            editable: false,
            useFilter: true, 
            mayBeHidden: false ,
            component: "deleteMe"
        },
        ]
    }),
```

Note that on the component hash you get to specify any additional properties and the actions you want.

https://github.com/onechiporenko/ember-models-table/blob/master/tests/dummy/app/templates/examples/custom-components-in-cell.hbs

**Comment by remadex** [comment]
Thanks ! It works ! ;)

**Comment by wonderful123** [comment]
Is there some more information about using the component hash. I'm not sure I understand how it works. The example doesn't really follow the ember guide of actions. At least I can't understand it.

**Comment by sutharmonil** [comment]
I was not able to find any of the advice given here in a document or sample. Most of the attributes invoked here are not very obvious to me, if there is a sample I could follow please let me know.

**Comment by cah-briangantzler** [comment]
This component, ember-models-table, creates the component for you in its code using the {{component }} helper. It does this by using the name of the component you specify. However, with only the name, there is no way for you to specify additional properties including actions.  

What the component hash is doing is giving you the control to create the component yourself using the {{component }} helper. Now you are able to specify those additional properties. You give that component a name in the component hash, then in the column array you use that name to say that defined component (with additional properties) goes in this column.

When models table goes to create the column, it looks to see if the name is in the component hash, if it is, it uses that component definition instead of using the {{component }} helper to create one.

I think the reason this isnt documented well is that is is really just a use of the {{component }} helper for [Contextual Components](https://guides.emberjs.com/release/in-depth-topics/patterns-for-components/#toc_contextual-components) as documented by ember.

As my personal note: I used this component for a while (and actually did the implementation of this specific feature. It has to be done this way because models table uses an array to define the components and not the hbs).  If this works for you, great. If does allow for reordering the columns by just changing the positions of the columns in the array. If you need that, stick with this component.   I however switched to [ember-yeti-table](https://github.com/miguelcobain/ember-yeti-table) because it makes your specific problem so much easier to understand. It does this by actually defining the table in the hbs rather than an array in javascript. However that does make ordering the columns much more difficult. Evaluate each and use the one that best suits your needs.

**Comment by sutharmonil** [comment]
If I write my models table like this:
@cah-briangantzler 

`<ModelsTable @data={{this.data}} @columns={{this.columns}}
@columnComponents={{hash
    deleteRow=(
      component "users/delete-row"
      onClick=this.deleteRecord
      handleDelete = this.deleteRecord
    )}}
@useFilteringByColumns={{this.useFilteringByColumns}} @showColumnsDropdown={{this.showColumnsDropdown}}
@showComponentFooter={{this.showComponentFooter}} @useNumericPagination={{this.showComponentFooter}}
@showCurrentPageNumberSelect={{this.showCurrentPageNumberSelect}} />`

How do I get the current row in my this.deleteRecord? And also, onClick does not seem to work here.

**Comment by cah-briangantzler** [comment]
the current row is assigned to a variable record on our component for you. so you would refer to the current row as @record in your hbs or this.record in your javascript (this.args.record if glimmer component)

Would need more detail on how you are implementing the onClick handler in the component to diagnose. However, because the component template is created outside of the loop, there is no way to directly call a passed action and get access to the current row. You will have to implement an onClick handler in your component, and call the passed action with record.

In the docs there is an example of implementing a delete row component. I see if it using the old style click method. You should use the on modifier if available.

http://onechiporenko.github.io/ember-models-table/v.3/bs3/#/examples/custom-components-in-cell

**Comment by sutharmonil** [comment]
Thanks a lot for the the `record = this.args?.record;` it worked!

Here is the component implementation for the delete button which is supposed to delete the record via an api call :
JS-> 
`import Component from '@glimmer/component';
import { action } from '@ember/object';
import { inject as service } from '@ember/service';
import { tracked } from '@glimmer/tracking';

export default class UsersDeleteRowComponent extends Component {
    handleDelete = this.args?.handleDelete;
    record = this.args?.record;
    @action 
    buttonClicked(params) {
        console.log('Delete was clicked on Users Grid: ', this.record);
        this.handleDelete();
    }
}`
HBS->
`<button type="button" class="btn btn-default" {{on 'click' (fn this.buttonClicked)}}>
  Delete
</button>`
Here, I am passing in the handleDelete function from the grid view HBS where this component is being called, And in turn this function is being passed from the main template which called the Grid View HBS, so this function is being linked directly to the controller action.

**Comment by cah-briangantzler** [comment]
You dont have to assign to locals first and I would think you would want this.
```
this.args.handleDelete(this.args.record);
```

You dont really need the ? as you are not checking for undefined on handleDelete or record. Which is fine, they are required in your implementation and if not present should throw an error.
