### ISSUE TITLE
Inline editing

### ISSUE THREAD

**Issue by onechiporenko** [onechiporenko/ember-models-table#37]
It would also be great if you could bind to a list of ember-data models thereby allowing inline editing.

From #34

**Comment by zardaloop** [comment]
I guess to make it editable we can add a custom template and inside the custom template having 
`{{input value=(get record column.propertyName)}}`

**Comment by cah-briangantzler** [comment]
See https://github.com/onechiporenko/ember-models-table/issues/270

**Comment by cah-briangantzler** [comment]
Here is a first pass at in-line editing https://github.com/bgantzler/ember-models-table/tree/edit. It is not complete

Wanted to talk with you on some design features, not sure if this is the correct place or not. Start up an email?

Some details
* The Row keeps track if the row is in edit or not.
* Using the ability to add components with actions, create a component that understanding editing to allow toggle to edit mode, save, and cancel (This component could be part of models-table, since its pretty generic, or could just be left to the user to implement as needed)
* Save and cancel currently have no default action, must be supplied by the users action. Wanted the minimal logic in the component for more flexibility
* Cell was not used before but the data was rendered in row. Cell is now always used. Will allow more consistent overriding.

**Comment by onechiporenko** [comment]
@cah-briangantzler, sorry for such delay. I think this issue is a good place for conversation. About details you've provided. They look good to me. Here what I thinking about:
* Every row has own state like `read/edit`
* Custom component for row in the "edit"-state. This component may be like a placeholder where user must implemenent its own logic and layout (one may use ember-bootstrap forms, another may use something else).
* Save-handler should just send edited data to the parent scope.
* Cancel-handler must not use `rollbackAttributes` or any specific ember-data methods, because models-table may be used not only with ember-data.
* Both save and cancel handlers must set row-state to the `read`-mode.
* Current `cell`-component may be used only as parent-component for cells in the "edit"-row. It will havw custom layout and use only `tagName` and some classes from the parent component.
* Row should be set to "edit"-mode  by special handler that may be used anywhere in the row (like some button the cell or double-click handler for row).

Some of items from this list are same as you mentioned above, some are not. Looking forward to your opinion.

**Comment by cah-briangantzler** [comment]
@onechiporenko 

Have you cloned my repo and ran the demo in the edit branch? I think I have everything you have suggested with the exception of the save and cancel handlers. Since the component to control the edit / save / cancel buttons is completed provided by the demo (not in the add-on) there is no need for those, it is completely under the control of the user.

I would like to finalize this and get it merged in, then the next step could be determining if a edit/save/cancel control should be provided by the add-on so the user would not have to implement it themselves. How that is implemented would determine the need for a save and cancel handler.

I implemented a default edit (an input). This is used if the column is editable and an edit component is not provided. If the user wanted to override this everywhere, its really as easy as providing an the same editComponent on each column. **Do you want a cell-edit in the theme?**

Ember-models-tables interface to components for the more part is record/propertyName. You cant really just substitute say ember-oneway-input because currently the input uses two-way binding and oneway uses a readonly value and an action. If the user wants oneway-input they would have to wrap a component around it to translate record/propertyName to value/action. Theres no real way to predict the interface to any component designed to edit, so the most basic default is provided.

One could make another addon that wraps all the oneway controls for use in models table, but i didnt see a way of using them directly.

Currently whats missing from the demo is all the tests for all the changes. I will be working on those when I have the time. Didnt want to write them all and you want something completely different.

**Comment by onechiporenko** [comment]
@cah-briangantzler, I've written my suggestions just to insure that I didn't miss something.
I have cloned your repo and checked what it's done. This is looks realy awesome and I'll gladly do merge when this feature is completed!

> the next step could be determining if a edit/save/cancel control should be provided by the add-on so the user would not have to implement it themselves. How that is implemented would determine the need for a save and cancel handler.

Addon may provide some default button-components with `messages` like 'Edit', 'Cancel', 'Save'. Clicking on each will send some named action with a row-data. However user should be able to set its custom components (even extending defaults).

> Do you want a cell-edit in the theme?

I think yes. As for me every component in the dir `component/models-table` must in the `theme.components`-config.

**Comment by cah-briangantzler** [comment]
Currently there are failing tests in the master branch, so I dont think I can submit my request until those are fixed.

Previously the default display of a cell was actually rendered in row. To be consistent row now displays cell all the time. I created a cell-content-display to be the old display of cell and also created a cell-content-edit. But for backward compatibility, had to make them tag-less, so although there are entries in the theme they arent being used because tag-less components cant have classes.

**Comment by bgantzler** [comment]
Have submitted pull request https://github.com/onechiporenko/ember-models-table/pull/279

**Comment by cah-briangantzler** [comment]
Pull request https://github.com/onechiporenko/ember-models-table/pull/280 has been merged.

Please close this issue. If there are any specific problems with inline editing, open a new issue with the specifics
